name: "Josh Kramer | Blog"

description: "The blog of Josh Kramer"

url: "http://localhost:3000"
#url: "http://joshkra.me"

paginate: 10

markdown: rdiscount
pygments: true

permalink: "/blog/:year/:month/:day/:title.html"